#ifndef SDK_CONFIG_H
#define SDK_CONFIG_H

#define NRF_SDH_ENABLED 1
#define NRF_SDH_BLE_ENABLED 1
#define NRF_SDH_BLE_VS_UUID_COUNT 1
#define NRF_SDH_BLE_GAP_DATA_LENGTH 27
#define NRF_SDH_BLE_PERIPHERAL_LINK_COUNT 1
#define NRF_SDH_BLE_TOTAL_LINK_COUNT 1

#define BLE_ADVERTISING_ENABLED 1
#define BLE_ADVERTISING_ADV_INTERVAL 64

#define BLE_GATTS_ENABLED 1
#define BLE_GATTS_ATTR_TAB_SIZE 1408

#define APP_TIMER_ENABLED 1
#define APP_TIMER_CONFIG_RTC_FREQUENCY 0
#define APP_TIMER_CONFIG_IRQ_PRIORITY 6

#define NRFX_SPI_ENABLED 1
#define NRFX_SPI0_ENABLED 1
#define SPI_ENABLED 1
#define SPI0_ENABLED 1
#define SPI_DEFAULT_CONFIG_FREQUENCY 0x02000000
#define SPI_DEFAULT_CONFIG_MODE 0
#define SPI_DEFAULT_CONFIG_BIT_ORDER 0
#define SPI_DEFAULT_CONFIG_IRQ_PRIORITY 6

#define NRF_LOG_ENABLED 1
#define NRF_LOG_BACKEND_UART_ENABLED 1
#define NRF_LOG_DEFAULT_LEVEL 3

#define NRF_PWR_MGMT_ENABLED 1
#define NRF_FSTORAGE_ENABLED 1
#define FDS_ENABLED 1

#define RETARGET_ENABLED 1

#endif // SDK_CONFIG_H
